### ISSUE TITLE
use input type=file

### ISSUE THREAD

**Issue by determinate** [thomasduft/formdef#1]
how to use in fromdef input type file?

**Comment by determinate** [comment]
Hello, Thomas! How I can update dynamically hidden editor value on Slot?

**Comment by thomasduft** [comment]
Hi determinate
I added a sample of how to upload a file. See [here](https://github.com/thomasduft/formdef/blob/e6aabb05c4e714de89d6d84064783cc472bd9cbe/src/app/simple/simple.component.ts#L27).
Hope that helps!
Greets Thomas
