### ISSUE TITLE
Nested Slot - Cannot read property 'injector' of undefined

### ISSUE THREAD

**Issue by simonedalfior-enerj** [thomasduft/formdef#3]
Hello Thomas, 
I'm trying to use nested slot in Angular UI but i have this error:

SlotComponent.html:15 ERROR TypeError: Cannot read property 'injector' of undefined
    at SlotHostComponent.ngOnInit (slotHost.component.ts:54)
    at checkAndUpdateDirectiveInline (core.js:24503)
    at checkAndUpdateNodeInline (core.js:35163)
    at checkAndUpdateNode (core.js:35102)
    at debugCheckAndUpdateNode (core.js:36124)
    at debugCheckDirectivesFn (core.js:36067)
    at Object.eval [as updateDirectives] (SlotComponent.html:15)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:36055)
    at checkAndUpdateView (core.js:35067)
    at callViewAction (core.js:35433)
	
In slotHost.component.ts,  property slotContent is undefined. 

This is my Slot:
`export class GroupDetailSlot implements Slot {
  public static KEY = 'groupdetailslot';

  public key = GroupDetailSlot.KEY;
  public type = SINGLE_SLOT;
  public title = '';
  public editors: Editor[];
  public children: Slot[];

  public constructor(
    companies: Array<Company>
  ) {
    const options = companies.map(
      (a: Company) => {
        return { key: a.companyId, value: a.companyName };
      });

    this.editors = [
      {
        key: 'id',
        type: NUMBER_EDITOR,
        label: 'Id',
        required: true
      },
      {
        key: 'name',
        type: TEXT_EDITOR,
        label: 'Name',
        required: true
      },
      {
        key: 'companyId',
        type: SELECT_EDITOR,
        label: 'Company',
        required: false,
        options: options,
        singleSelection: true,
        bindingBehaviour: "key"
      }
    ];
    this.children = [
      {
        key: 'users',
        type: ARRAY_SLOT,
        title: '',
        editors: [
          {
            type: TEXT_EDITOR,
            key: 'userIdjcrm',
            label: 'Number',
            required: true,
          }
        ],
        children: []
      }
    ];
  }
}`

Is it the right way to use nested slot?

Thanks,
Simon

**Comment by thomasduft** [comment]
Hi Simon
Well, I wonder where you found the SlotHostComponent in this repository. There isn't such a component in this repo. There is one in the microwf samples. There I use an advanced formdef implementation if you want.

But to your question: For me your sample seems ok. The most often forgotten part is that you did not register your custom slot within the components NgModule (see [here](https://github.com/thomasduft/formdef/blob/f3f60e4622dfeb7eab60ec128f9f757f678473fa/src/app/nested/nested.module.ts#L27)).

Hope this helped.

Thomas

**Comment by simonedalfior-enerj** [comment]
Hi Thomas,
I'm working with microwf sample but I've opened an issue here, in the formdef repo.
Component is not registered in NgModule but in ngOnInit (look at thi [issue])(https://github.com/thomasduft/formdef/issues/2).

**Comment by simonedalfior-enerj** [comment]
Hi Thomas, 
I've registered the slot component in NgModule but have the same problem.
In SlotHostComponent, @ViewChild don't find **slotContent** element. 
What about closing this issue and open a new one in che microwf repo?

Thanks, 
Simone

**Comment by thomasduft** [comment]
Hi Simon
That won't change anything. Since I do not know your code and so far I can live with the implementation I show here on github it is not changing anything. 

Best would be if you setup a working sample that demonstrates the issue on [stackblitz](https://stackblitz.com/edit/angular-3yytut) or so and send me the link. Afterwards I can have a look.

Have a nice day,

Thomas

**Comment by simonedalfior-enerj** [comment]
Ok, I'm gonna try the stackblitz way.
Is there a working sample of nested slot in microwf repo?

Thanks,
Simon

**Comment by thomasduft** [comment]
Hi
No there isn't one. The one that exists, but without the slotHost feature is the [stackblitz sample](https://stackblitz.com/edit/angular-ywtd5l) for my this repo.

An event better approach would be to make a PR and incorporate the slotHost feature within this repo. I will create a new branch for that intention and upgrade to the latest ng packages til this evenening.

Stay tuned.

Thomas

**Comment by thomasduft** [comment]
Hi Simon
Fixed it! Checkout the [stackblitz sample](https://stackblitz.com/github/thomasduft/formdef) that runs on this repo!

Have a nice day!

Thomas

**Comment by simonedalfior-enerj** [comment]
Thanks a lot Thomas! 

Have a nice day
Simon
